application/services/users/models.py
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash

from application.utils.database import db


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(80), unique=True, nullable=False)
    password_hash = db.Column(db.String(120))

    def __repr__(self):
        return f'<User {self.username}>'

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def save_to_db(self):  # inserting and updating data to database
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self):
        db.session.delete(self)
        db.session.commit()

application/__init__.py
import os

from flask import Flask, g, session
from flask import render_template
from flask_login import login_required
from flask_debugtoolbar import DebugToolbarExtension

# Configs
from application import config
# Object to work with DB
from application.utils.database import db
# Services
from application.services.users.views import user_bp
# Helpers
from application.utils.login import login
from application.utils.migrate import migrate
from application.utils.helpers.custom_exceptions import IncorrectEnvSet
from application.utils.helpers.view_helper import sign_in_required


def create_tables(app) -> None:
    """
    Need this function to create all tables from ALL modes in app.

    IMPORTANT: we need to import ALL models here (before usging create_all() method),
    otherwise, "db" object won't see our models and will ignore creating actual tables.

    :return: None
    """
    db.init_app(app)
    with app.app_context():
        db.create_all()


def create_app():
    # create app
    app = Flask(__name__, instance_relative_config=True)

    # select ENV
    if os.environ.get('FLASK_ENV') == 'development':
        cfg = config.DevelopmentConfig()
    elif os.environ.get('FLASK_ENV') == 'production':
        cfg = config.ProductionConfig()
    elif os.environ.get('FLASK_ENV') == 'testing':
        cfg = config.TestingConfig()
    else:
        raise IncorrectEnvSet('Incorrect ENV was set!')
    # configure the app
    app.config.from_object(cfg)
    # additional configs
    app.config['SQLALCHEMY_DATABASE_URI'] = cfg.DATABASE_URI

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    # create tables in Database
    create_tables(app)

    migrate.init_app(app, db)
    login.init_app(app)
    login.login_view = 'user_service.sign_in'

    # debug
    toolbar = DebugToolbarExtension(app)

    # register blueprints
    app.register_blueprint(user_bp)

    # a simple page that says hello
    @app.route('/')
    @login_required
    def index():
        return render_template('index.html')

    return app

application/services/users/views.py
from flask import Blueprint
from flask import render_template, redirect, flash
from flask import request, session, url_for, g
from flask_login import current_user, login_user, logout_user

from application.services.users.models import User
from application.utils.login import login

user_bp = Blueprint('user_service', __name__, url_prefix='/user')


@user_bp.route('/signup', methods=('GET', 'POST'))
def sign_up():
    if current_user.is_authenticated:
        return redirect(url_for('index'))

    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        email = request.form['email']
        error = None

        if not username:
            error = 'Username is required'
        elif not password:
            error = 'Password is required'
        user = User.query.filter_by(username=username).first()
        if user is not None:
            error = f'User {username} is already exists'

        if error is None:
            new_user = User(username=username, email=email)
            new_user.set_password(password)
            new_user.save_to_db()
            return redirect(url_for('user_service.sign_in'))
        
        flash(error)

    return render_template("auth/sign_up.html")


@user_bp.route('/signin', methods=('GET', 'POST'))
def sign_in():
    if current_user.is_authenticated:
        return redirect(url_for('index'))

    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        error = None

        user = User.query.filter_by(username=username).first()
        if user is None:
            error = 'Incorrect username!'
        elif not user.check_password(password):
            error = 'Incorrect password!'

        if error is None:
            login_user(user)
            return redirect(url_for('index'))

        flash(error)

    return render_template("auth/sign_in.html")


@user_bp.route('/signout')
def sign_out():
    logout_user()
    return redirect(url_for('index'))


@login.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

application/templates/base.html
<!doctype html>
<head>
    <script type="module" src="https://unpkg.com/ionicons@5.4.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule="" src="https://unpkg.com/ionicons@5.4.0/dist/ionicons/ionicons.js"></script>
    <title>Web Money Manager{% block title %}{% endblock %}</title>
    {% block head %}

    {% endblock %}
</head>
<body>
<header>
    {% block header %}

    {% endblock %}
</header>
<section class="content">
    {% block content %}

    {% endblock %}
</section>

{% block additionalScripts %}

{% endblock %}
</body>

application/templates/index.html
{% extends 'base.html' %}

{% block title %}: Dashboard {% endblock %}

{% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>Dashboard Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard/">


    <!-- Bootstrap core CSS -->
    <link href="../static/assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>

    <!-- Custom styles for this template -->
    <link href="../static/css/dashboard.css" rel="stylesheet">
{% endblock %}

{% block header %}
    <nav class="navbar navbar-dark navbar-expand-lg bg-dark shadow">
        <div class="container-fluid">
            <div class="left-panel">
                <a id="sideMenuTrigger" href="#">
                    <input type="checkbox" id="checkbox3" class="checkbox3 visuallyHidden">
                    <label for="checkbox3">
                        <div class="hamburger hamburger3">
                            <span class="bar bar1"></span>
                            <span class="bar bar2"></span>
                            <span class="bar bar3"></span>
                            <span class="bar bar4"></span>
                        </div>
                    </label>
                    <i id="hamburger-menu" class="hamburger align-self-center"></i>
                </a>
                <input class="form-control form-control-dark" type="text" placeholder="Search..." aria-label="Search">
            </div>
            <div class="right-panel">
                <div id="new-expense-btn">
                    New Expense
                </div>
                <li class="nav-item dropdown user-menu-dropdown-container">
                    {% if current_user.is_authenticated %}
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown"
                           aria-expanded="false">
                            <img src="../static/assets/brand/person-circle-sharp.svg" alt="" width="40" height="40">
                            <span>{{ current_user.username }}</span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Profile</a></li>
                            <li><a class="dropdown-item" href="#">Settings</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{{ url_for('user_service.sign_out') }}">Sign out</a></li>
                        </ul>
                    {% else %}
                        <a class="nav-link dropdown-toggle" href="{{ url_for('user_service.sign_in') }}"
                           id="navbarDropdown"
                           role="button"
                           data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Sign in/up
                        </a>
                    {% endif %}
                </li>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div id="row" class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">
                            <span data-feather="home"></span>
                            Dashboard
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="bar-chart-2"></span>
                            Statistics
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="users"></span>
                            Accounts
                        </a>
                    </li>
                </ul>

                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>Saved reports</span>
                    <a class="link-secondary" href="#" aria-label="Add a new report">
                        <span data-feather="plus-circle"></span>
                    </a>
                </h6>
                <ul class="nav flex-column mb-2">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Current month
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Last quarter
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Social engagement
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Year-end sale
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
{% endblock %}

{% block additionalScripts %}
    <script src="../static/assets/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"
            integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"
            integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha"
            crossorigin="anonymous"></script>
    <script src="../static/js/dashboard.js"></script>
{% endblock %}

application/templates/user/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>